### ISSUE TITLE
Python 3.11 Compatibility Issue

### ISSUE THREAD

**Issue by vatsalvora** [MrPowers/farsante#3]
I am getting a pickling error when trying to use Python 3.11. It was working correctly with Python 3.10.

_pickle.PicklingError: Could not serialize object: IndexError: tuple index out of range

**Comment by MrPowers** [comment]
@vatsalvora - thanks for opening this.  Can you please paste the Farsante code you were running, so I can reproduce on my end and try to figure out a solution?

**Comment by vatsalvora** [comment]
Realized it was a Python/spark compatibility issue. For spark 3.3.x you can only use Python 3.10.

**Comment by MrPowers** [comment]
@vatsalvora - glad you figured it out!
